name: polymaking
version: "0.8.8"
license: "GPL-2.0-or-later"
date: 2025-12-03
description: |
    Interfacing the geometry software polymake

authors:
    - name: Marc Roeder
      url: mailto:roeder.marc@gmail.com

maintainers:
    - name: Marc Roeder
      url: mailto:roeder.marc@gmail.com
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.8"

www: https://gap-packages.github.io/polymaking/
readme: README.md
packageinfo: https://gap-packages.github.io/polymaking/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/polymaking/releases/download/v0.8.8/polymaking-0.8.8.tar.gz

abstract: |
    This package provides a very basic interface to the polymake program by Ewgenij Gawrilow, Michael Joswig et al.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    interface, polymake, computational geometry.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>RT25</span>]   <b class='BibAuthor'>Roeder, M. and GAP Team, T.</b>,
     <i class='BibTitle'>polymaking, Interfacing the geometry software polymake,
             Version 0.8.8</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/polymaking/">https://gap-packages.github.io/polymaking/</a></span>.
    </p>
    

bibtex: |
    @misc{ polymaking,
      author =           {Roeder, M. and GAP Team, T.},
      title =            {{polymaking},   {Interfacing   the  geometry  software
                          polymake}, {V}ersion 0.8.8},
      month =            {Dec},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href     {https://gap-packages.github.io/polymaking/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{polymaking/}}},
      keywords =         {interface; polymake; computational geometry},
      printedkey =       {RT25}
    }

